---
# main tasks for python - skip if python found

- stat: path='{{ python_python }}'
  register: python_python
  tags: [python, build]
  
- import_tasks: build.yml
  become: yes
  tags: [python, build]
  when: not python_python.stat.exists
